version: "3.9"
services:
  MSCGenginx:
    image: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html
      - ./config/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  mscgen_backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app